apiVersion: apps/v1
kind: Deployment
metadata:
  name: asset-management-backend
  namespace: asset-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asset-management-backend
  template:
    metadata:
      labels:
        app: asset-management-backend 
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /app/uploads/assets && chown -R 1000:1000 /app/uploads"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads

      containers:
        - name: asset-management-backend 
          image: baeseokin/asset-management-backend:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          volumeMounts:
            - name: uploads-volume
              mountPath: /app/uploads
          env:
            - name: DB_HOST
              value: "mariadb-service.report"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "assetuser"
            - name: DB_PASSWORD
              value: "assetpass"
            - name: DB_NAME
              value: "assetdb"
            - name: CORS_ORIGIN
              value: "http://localhost:30006,http://localhost:30005,http://localhost:5173"
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: asset-management-uploads-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: asset-management-backend 
  namespace: asset-management
spec:
  selector:
    app: asset-management-backend 
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30005
  type: NodePort
